var MSG = {
  title: "代码",
  blocks: "Blockly 编程",
  linkTooltip: "保存模块并生成链接。",
  runTooltip: "于工作区中运行块所定义的程式。",
  badCode: "程序错误：\n%1",
  timeout: "超过最大执行行数。",
  trashTooltip: "放弃所有块。",
  catLogic: "逻辑",
  catLoops: "循环",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catColour: "颜色",
  catVariables: "变量",
  catFunctions: "函数",
  listVariable: "列表",
  textVariable: "文本",
  httpRequestError: "请求存在问题。",
  linkAlert: "通过这个链接分享您的模块：\n\n%1",
  hashError: "对不起，没有任何已保存的程序对应'%1' 。",
  xmlError: "无法载入您保存的文件。您是否使用其他版本的Blockly创建该文件的？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”以取消您对XML的修改，或选择“取消”以继续编辑XML。",
  saveTooltip: "保存块文件",
  loadTooltip: "加载块文件",
  notificationTooltip: "通知面板",
  ErrorGET: "无法加载请求文件",
  invalidDevice: "设备无效",
  languageTooltip: "改变语言",
  noToolbox: "设备没有工具集",
  networkTooltip: "通过网络连接 (WebREPL, http).",
  serialTooltip: "通过串口或蓝牙 (Web Serial API, https).",
  toolbarTooltip: "显示工具栏",
  wrongDevicePin: "检查引脚，目标设备已改变",
  notDefined: "未定义",
  editAsFileValue: "编辑文件",
  editAsFileTooltip: "编辑python代码并保存到设备",
  forumTooltip: "帮助论坛",
  blocksLoadedFromFile: "已加载块文件 '%1'",
  deviceUnavailable: "设备 '%1' 不可用.",
  notConnected: "未连接设备",
  serialFroozen: "串口连接未响应",
  notAvailableFlag: "$1 is not available on your browser.\r\nPlease make sure the $1 flag is enabled."
};
